AllCops:
  Include:
    - '**/Berksfile'
    - '**/Cheffile'
  Exclude:
    - 'metadata.rb'
    - 'cookbooks/**/*'

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 100

Style/IfUnlessModifier:
  MaxLineLength: 120

Style/WhileUntilModifier:
  MaxLineLength: 120

Metrics/BlockLength:
  Enabled: false
